sources:
  - name: raw
    database: netflix  
    schema: raw  
    tables:
      - name: raw_movies
      - name: raw_links
      - name: raw_tags
      - name: raw_ratings
      - name: raw_genome_tags
      - name: raw_genome_scores